# Utiliza una imagen base oficial de Python
FROM python:3.10-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de requerimientos si existe (asegúrate de tener un requirements.txt)
COPY requirements.txt requirements.txt

# Instala las dependencias desde requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el contenido de la carpeta actual (fase-2) al directorio de trabajo en el contenedor
COPY . .

# Ejecuta los scripts de entrenamiento y predicción
RUN python scripts/train.py
RUN python scripts/predict.py

# Exponer el puerto para la API REST
EXPOSE 5000

# Comando por defecto para iniciar la API
CMD ["flask", "apirest:app", "--host", "0.0.0.0", "--port", "5000"]
